myName = input("What's your name? ")
myFood = input("What is your favorite food? ")
myMusic = input("What is your favorite music? ")
myLocation = input("Where do you live? ")


print()
print("So, you are")
print(myName)
print("from ")
print(myLocation)
print("Your favorite food is ")
print(myFood)
print("and you like to listen to ")
print(myMusic)
print() 
print ("Have a great day!")